version: '3'

services:
  web:
    image: ${DOCKER_IMAGE}
    ports:
      - "${APP_PORT}:80"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=DSPProject2024
      - MYSQL_DB=applications
    volumes:
      - ./src:/var/www/html/
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DSPProject2024
      MYSQL_DATABASE: applications
      MYSQL_USER: root
      MYSQL_PASSWORD: DSPProject2024
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
