services:
  web:
    image: ${DOCKER_IMAGE}
    ports:
      - "${APP_PORT}:80"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: DSPProject2024
      MYSQL_DB: applications
    volumes:
      - ./src:/var/www/html:rw
    depends_on: 
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DSPProject2024
      MYSQL_DATABASE: applications
    ports:
      - "${APP_DB_PORT}:3306"
    command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --bind-address=0.0.0.0
    volumes:
      - db_data:/var/lib/mysql
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "${APP_PORT_PHPMYADMIN}:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: DSPProject2024

volumes:
  db_data: